In [1]:
import pandas as pd
import os
import numpy as np

In [3]:
data_folder="./Data/current_FAO/raw_files/"
for file in os.listdir(data_folder):
    file=data_folder+file
    print("\n"+file)
    try:
        print(pd.read_csv(file,nrows=2).head())
    except:
       pass

./Data/current_FAO/raw_files/ASTI_Research_Spending_E_All_Data_(Norm).csv
   Country Code  Country  Item Code                           Item  \
0             4  Algeria      23045  Agriculture research spending
1             4  Algeria      23045  Agriculture research spending

   Element Code                                            Element  Year Code  \
0          6083  Share of Value Added (Agriculture, Forestry an...       2009
1          6083  Share of Value Added (Agriculture, Forestry an...       2010

   Year  Unit  Value Flag
0  2009   NaN   0.18   AS
1  2010   NaN   0.18   AS

./Data/current_FAO/raw_files/ASTI_Researchers_E_All_Data_(Norm).csv
   Country Code  Country  Item Code                            Item  \
0             4  Algeria      23046  Agricultural researchers (FTE)
1             4  Algeria      23046  Agricultural researchers (FTE)

   Element Code Element  Year Code  Year Unit  Value Flag
0          6085  Number       2009  2009   No  510.3   AS
1          6085  Number       2010  2010   No  529.1   AS

./Data/current_FAO/raw_files/CommodityBalances_Crops_E_All_Data_(Normalized).csv
   Area Code         Area  Item Code                 Item  Element Code  \
0          2  Afghanistan       2617  Apples and products          5510
1          2  Afghanistan       2617  Apples and products          5510

      Element  Year Code  Year    Unit    Value Flag
0  Production       1961  1961  tonnes  15100.0    S
1  Production       1962  1962  tonnes  15100.0    S

./Data/current_FAO/raw_files/CommodityBalances_LivestockFish_E_All_Data_(Normalized).csv
   Area Code         Area  Item Code         Item  Element Code     Element  \
0          2  Afghanistan       2731  Bovine Meat          5510  Production
1          2  Afghanistan       2731  Bovine Meat          5510  Production

   Year Code  Year    Unit    Value Flag
0       1961  1961  tonnes  43000.0    S
1       1962  1962  tonnes  45800.0    S

./Data/current_FAO/raw_files/ConsumerPriceIndices_E_All_Data_(Normalized).csv
   Area Code         Area  Item Code  \
0          2  Afghanistan      23013
1          2  Afghanistan      23013

                                         Item  Months Code   Months  \
0  Consumer Prices, Food Indices (2010 = 100)         7001  January
1  Consumer Prices, Food Indices (2010 = 100)         7001  January

   Year Code  Year  Unit       Value  Flag    Note
0       2012  2012   NaN  107.570513   NaN  2011M3
1       2013  2013   NaN  113.020082   NaN  2011M3

./Data/current_FAO/raw_files/Deflators_E_All_Data_(Normalized).csv
   Area Code         Area  Item Code          Item  Element Code  \
0          2  Afghanistan      22024  GDP Deflator          6133
1          2  Afghanistan      22024  GDP Deflator          6133

                             Element  Year Code  Year  Unit   Value Flag
0  Value Local Currency, 2005 prices       1970  1970   NaN  0.0229    *
1  Value Local Currency, 2005 prices       1971  1971   NaN  0.0241    *

./Data/current_FAO/raw_files/Emissions_Agriculture_Agriculture_total_E_All_Data_(Norm).csv
   Country Code      Country  Item Code                  Item  Element Code  \
0             2  Afghanistan       5058  Enteric Fermentation          7231
1             2  Afghanistan       5058  Enteric Fermentation          7231

             Element  Year Code  Year       Unit      Value Flag
0  Emissions (CO2eq)       1961  1961  Gigagrams  5054.3459    A
1  Emissions (CO2eq)       1962  1962  Gigagrams  5151.5228    A

./Data/current_FAO/raw_files/Emissions_Agriculture_Burning_crop_residues_E_All_Data_(Norm).csv
   Country Code      Country  Item Code   Item  Element Code  \
0             2  Afghanistan         56  Maize          7245
1             2  Afghanistan         56  Maize          7245

                       Element  Year Code  Year    Unit     Value Flag
0  Biomass burned (dry matter)       1961  1961  tonnes  500000.0   Fc
1  Biomass burned (dry matter)       1962  1962  tonnes  500000.0   Fc

./Data/current_FAO/raw_files/Emissions_Agriculture_Burning_Savanna_E_All_Data_(Norm).csv
   Country Code      Country  Item Code     Item  Element Code      Element  \
0             2  Afghanistan       6760  Savanna          7246  Burned Area
1             2  Afghanistan       6760  Savanna          7246  Burned Area

   Year Code  Year Unit   Value Flag
0       1990  1990   Ha  0.9251   Fc
1       1991  1991   Ha  0.9251   Fc

./Data/current_FAO/raw_files/Emissions_Agriculture_Crop_Residues_E_All_Data_(Norm).csv
   Country Code      Country  Item Code    Item  Element Code  \
0             2  Afghanistan         44  Barley         72392
1             2  Afghanistan         44  Barley         72392

                    Element  Year Code  Year             Unit         Value  \
0  Residues (Crop residues)       1961  1961  Kg of nutrients  5.925706e+06
1  Residues (Crop residues)       1962  1962  Kg of nutrients  5.925706e+06

  Flag
0   Fc
1   Fc

./Data/current_FAO/raw_files/Emissions_Agriculture_Cultivated_Organic_Soils_E_All_Data_(Norm).csv
   Country Code      Country  Item Code                    Item  Element Code  \
0             2  Afghanistan       6727  Cropland organic soils          5026
1             2  Afghanistan       6727  Cropland organic soils          5026

  Element  Year Code  Year Unit  Value  Flag
0    Area       1990  1990   Ha    0.0   NaN
1    Area       1991  1991   Ha    0.0   NaN

./Data/current_FAO/raw_files/Emissions_Agriculture_Energy_E_All_Data_(Norm).csv
   Country Code Country  Item Code            Item  Element Code  \
0           351   China       6801  Gas-Diesel oil         72184
1           351   China       6801  Gas-Diesel oil         72184

                      Element  Year Code  Year       Unit     Value Flag
0  Consumption in Agriculture       1986  1986  Terajoule  288659.0   Fc
1  Consumption in Agriculture       1987  1987  Terajoule  313771.0   Fc

./Data/current_FAO/raw_files/Emissions_Agriculture_Enteric_Fermentation_E_All_Data_(Norm).csv
   Country Code      Country  Item Code   Item  Element Code Element  \
0             2  Afghanistan       1107  Asses          5111  Stocks
1             2  Afghanistan       1107  Asses          5111  Stocks

   Year Code  Year  Unit      Value  Flag
0       1961  1961  Head  1300000.0   NaN
1       1962  1962  Head   851850.0   NaN

./Data/current_FAO/raw_files/Emissions_Agriculture_Manure_applied_to_soils_E_All_Data_(Norm).csv
   Country Code      Country  Item Code   Item  Element Code Element  \
0             2  Afghanistan       1107  Asses          5111  Stocks
1             2  Afghanistan       1107  Asses          5111  Stocks

   Year Code  Year  Unit      Value  Flag
0       1961  1961  Head  1300000.0   NaN
1       1962  1962  Head   851850.0   NaN

./Data/current_FAO/raw_files/Emissions_Agriculture_Manure_left_on_pasture_E_All_Data_(Norm).csv
   Country Code      Country  Item Code   Item  Element Code  \
0             2  Afghanistan       1107  Asses        723602
1             2  Afghanistan       1107  Asses        723602

                                             Element  Year Code  Year  \
0  Indirect emissions (N2O that leaches) (Manure ...       1961  1961
1  Indirect emissions (N2O that leaches) (Manure ...       1962  1962

        Unit   Value Flag
0  Gigagrams  0.0953   Fc
1  Gigagrams  0.0625   Fc

./Data/current_FAO/raw_files/Emissions_Agriculture_Manure_Management_E_All_Data_(Norm).csv
   Country Code      Country  Item Code   Item  Element Code Element  \
0             2  Afghanistan       1107  Asses          5111  Stocks
1             2  Afghanistan       1107  Asses          5111  Stocks

   Year Code  Year  Unit      Value  Flag
0       1961  1961  Head  1300000.0   NaN
1       1962  1962  Head   851850.0   NaN

./Data/current_FAO/raw_files/Emissions_Agriculture_Rice_Cultivation_E_All_Data_(Norm).csv
   Country Code      Country  Item Code         Item  Element Code  \
0             2  Afghanistan         27  Rice, paddy          5312
1             2  Afghanistan         27  Rice, paddy          5312

          Element  Year Code  Year Unit     Value  Flag
0  Area harvested       1961  1961   Ha  210000.0   NaN
1  Area harvested       1962  1962   Ha  210000.0   NaN

./Data/current_FAO/raw_files/Emissions_Agriculture_Synthetic_Fertilizers_E_All_Data_(Norm).csv
   Country Code      Country  Item Code  \
0             2  Afghanistan       3102
1             2  Afghanistan       3102

                                       Item  Element Code  \
0  Nitrogen Fertilizers (N total nutrients)        516202
1  Nitrogen Fertilizers (N total nutrients)        516202

                                            Element  Year Code  Year  \
0  Nitrogen fertilizer content applied that leaches       2002  2002
1  Nitrogen fertilizer content applied that leaches       2003  2003

              Unit      Value Flag
0  Kg of nutrients  7033800.0   Fc
1  Kg of nutrients  6096000.0   Fc

./Data/current_FAO/raw_files/Emissions_Land_Use_Burning_Biomass_E_All_Data_(Norm).csv
   Country Code      Country  Item Code                   Item  Element Code  \
0             2  Afghanistan       6796  Humid tropical forest          7246
1             2  Afghanistan       6796  Humid tropical forest          7246

       Element  Year Code  Year Unit  Value Flag
0  Burned Area       1990  1990   Ha    0.0   Fc
1  Burned Area       1991  1991   Ha    0.0   Fc

./Data/current_FAO/raw_files/Emissions_Land_Use_Cropland_E_All_Data_(Norm).csv
   Country Code      Country  Item Code                    Item  Element Code  \
0             2  Afghanistan       6727  Cropland organic soils          5026
1             2  Afghanistan       6727  Cropland organic soils          5026

  Element  Year Code  Year Unit  Value  Flag
0    Area       1990  1990   Ha    0.0   NaN
1    Area       1991  1991   Ha    0.0   NaN

./Data/current_FAO/raw_files/Emissions_Land_Use_Forest_Land_E_All_Data_(Norm).csv
   Country Code      Country  Item Code    Item  Element Code Element  \
0             2  Afghanistan       6661  Forest          5110    Area
1             2  Afghanistan       6661  Forest          5110    Area

   Year Code  Year     Unit   Value Flag
0       1990  1990  1000 Ha  1350.0    F
1       1991  1991  1000 Ha  1350.0    F

./Data/current_FAO/raw_files/Emissions_Land_Use_Grassland_E_All_Data_(Norm).csv
   Country Code      Country  Item Code                     Item  \
0             2  Afghanistan       6728  Grassland organic soils
1             2  Afghanistan       6728  Grassland organic soils

   Element Code Element  Year Code  Year Unit  Value  Flag
0          5026    Area       1990  1990   Ha    0.0   NaN
1          5026    Area       1991  1991   Ha    0.0   NaN

./Data/current_FAO/raw_files/Emissions_Land_Use_Land_Use_Total_E_All_Data_(Norm).csv
   Country Code      Country  Item Code         Item  Element Code  \
0             2  Afghanistan       5065  Forest land          7233
1             2  Afghanistan       5065  Forest land          7233

                        Element  Year Code  Year       Unit  Value Flag
0  Net emissions/removals (CO2)       1990  1990  Gigagrams    0.0    A
1  Net emissions/removals (CO2)       1991  1991  Gigagrams    0.0    A

./Data/current_FAO/raw_files/Employment_Indicators_E_All_Data_(Norm).csv
   Country Code      Country  Source Code            Source  Indicator Code  \
0             2  Afghanistan         3022  Household survey           21069
1             2  Afghanistan         3022  Household survey           21067

                                           Indicator  Year Code  Year Unit  \
0        Employment-to-population ratio, rural areas       2006  2006    %
1  Employment-to-population ratio, rural areas, f...       2006  2006    %

   Value Flag
0   47.1   XI
1   15.9   XI

./Data/current_FAO/raw_files/Environment_AirClimateChange_E_All_Data.csv
   CountryCode  Country  ItemCode                                      Item  \
0            3  Albania      6730  Ammonia (NH3) emissions from agriculture
1            3  Albania      6730  Ammonia (NH3) emissions from agriculture

   ElementGroup  ElementCode                                    Element  Year  \
0          7203         7203  % of total NH3 emissions from agriculture  1990
1          7203         7203  % of total NH3 emissions from agriculture  1991

  Unit  Value Flag
0    %  97.22   Fc
1    %  97.57   Fc

./Data/current_FAO/raw_files/Environment_Emissions_by_Sector_E_All_Data_(Normalized).csv
   Area Code         Area  Item Code  \
0          2  Afghanistan       6814
1          2  Afghanistan       6814

                                                Item  Element Code  \
0  Energy (energy, manufacturing and construction...          7231
1  Energy (energy, manufacturing and construction...          7231

             Element  Year Code  Year       Unit      Value Flag
0  Emissions (CO2eq)       1990  1990  Gigagrams   943.2945    A
1  Emissions (CO2eq)       1991  1991  Gigagrams  1022.1110    A

./Data/current_FAO/raw_files/Environment_Emissions_intensities_E_All_Data_(Normalized).csv
   Area Code         Area  Item Code                    Item  Element Code  \
0          2  Afghanistan       1718  Cereals excluding rice         71761
1          2  Afghanistan       1718  Cereals excluding rice         71761

               Element  Year Code  Year                 Unit   Value Flag
0  Emissions intensity       1961  1961  kg CO2eq/kg product  0.1191   Fc
1  Emissions intensity       1962  1962  kg CO2eq/kg product  0.1209   Fc

./Data/current_FAO/raw_files/Environment_Energy_E_All_Data.csv
   CountryCode           Country  ItemCode                  Item  \
0         5100  Africa + (Total)      6740  Bioenergy production
1         5100  Africa + (Total)      6740  Bioenergy production

   ElementGroup  ElementCode  \
0          7204        72041
1          7204        72041

                                             Element  Year Unit  Value Flag
0  Bioenergy production as a % of total renewable...  1971    %  97.91   Fc
1  Bioenergy production as a % of total renewable...  1972    %  97.48   Fc

./Data/current_FAO/raw_files/Environment_Fertilizers_E_All_Data_(Normalized).csv
   Area Code         Area  Item Code  \
0          2  Afghanistan       3102
1          2  Afghanistan       3102

                                       Item  Element Code  \
0  Nitrogen Fertilizers (N total nutrients)          5159
1  Nitrogen Fertilizers (N total nutrients)          5159

                            Element  Year Code  Year   Unit  Value Flag
0  Average use per area of cropland       2002  2002  kg/ha   3.02   Fc
1  Average use per area of cropland       2003  2003  kg/ha   2.57   Fc

./Data/current_FAO/raw_files/Environment_LandCover_E_All_Data_(Normalized).csv
   Area Code         Area  Item Code  \
0          2  Afghanistan       6970
1          2  Afghanistan       6970

                                                Item  Element Code  \
0  Artificial surfaces (including urban and assoc...          5007
1  Artificial surfaces (including urban and assoc...          5007

           Element  Year Code  Year     Unit    Value Flag
0  Area from MODIS       2001  2001  1000 ha  71.0899   FC
1  Area from MODIS       2002  2002  1000 ha  71.0770   FC

./Data/current_FAO/raw_files/Environment_LandUse_E_All_Data_(Normalized).csv
   Area Code         Area  Item Code         Item  Element Code  \
0          2  Afghanistan       6621  Arable land          7208
1          2  Afghanistan       6621  Arable land          7208

                      Element  Year Code  Year Unit  Value Flag
0  Share in Agricultural area       1961  1961    %  20.29   Fc
1  Share in Agricultural area       1962  1962    %  20.39   Fc

./Data/current_FAO/raw_files/Environment_Livestock_E_All_Data.csv
   CountryCode      Country  ItemCode                            Item  \
0            2  Afghanistan      1746  Cattle and Buffaloes + (Total)
1            2  Afghanistan      1746  Cattle and Buffaloes + (Total)

   ElementGroup  ElementCode               Element  Year Unit  Value Flag
0          7211         7211  % of Total Livestock  1961    %   9.73   Fc
1          7211         7211  % of Total Livestock  1962    %  10.55   Fc

./Data/current_FAO/raw_files/Environment_LivestockPatterns_E_All_Data_(Normalized).csv
   Area Code         Area  Item Code   Item  Element Code  \
0          2  Afghanistan       1107  Asses          7213
1          2  Afghanistan       1107  Asses          7213

                                         Element  Year Code  Year    Unit  \
0  Density of livestock in the agricultural area       1961  1961  LSU/ha
1  Density of livestock in the agricultural area       1962  1962  LSU/ha

   Value Flag
0   0.02   Fc
1   0.01   Fc

./Data/current_FAO/raw_files/Environment_Pesticides_E_All_Data_(Normalized).csv
   Area Code     Area  Item Code        Item  Element Code  \
0          3  Albania       1357  Pesticides          5159
1          3  Albania       1357  Pesticides          5159

                            Element  Year Code  Year   Unit  Value Flag
0  Average use per area of cropland       1993  1993  kg/ha   0.17   Fc
1  Average use per area of cropland       1994  1994  kg/ha   0.29   Fc

./Data/current_FAO/raw_files/Environment_Soil_E_All_Data.csv
   CountryCode      Country  ItemCode  Item  ElementGroup  ElementCode  \
0            2  Afghanistan      6709  Soil          7219         7219
1            2  Afghanistan      6709  Soil          7220         7220

                                             Element  Year     Unit  Value  \
0  Average soil erosion expressed in GLASOD erosi...  1991  degrees   0.22
1  Average land degradation in GLASOD erosion degree  1991  degrees   2.64

   Flag
0   NaN
1   NaN

./Data/current_FAO/raw_files/Environment_Temperature_change_E_All_Data_(Normalized).csv

./Data/current_FAO/raw_files/Environment_Water_E_All_Data.csv
   CountryCode      Country  ItemCode                                   Item  \
0            2  Afghanistan      6720  Water withdrawal for agricultural use
1            3      Albania      6720  Water withdrawal for agricultural use

   ElementGroup  ElementCode                      Element  Year Unit  Value  \
0          7222         7222  % of total water withdrawal  1987    %  99.00
1          7222         7222  % of total water withdrawal  1990    %  83.33

  Flag
0   Fc
1   Fc

./Data/current_FAO/raw_files/Exchange_rate_E_All_Data_(Normalized).csv
   Area Code         Area  Item Code           Item ISO Currency Code  \
0          2  Afghanistan      22027  Exchange rate               AFN
1          2  Afghanistan      22027  Exchange rate               AFN

  Currency  Year Code  Year  Unit  Value Flag
0  Afghani       1970  1970   NaN  0.045  XAM
1  Afghani       1971  1971   NaN  0.045  XAM

./Data/current_FAO/raw_files/Food_Aid_Shipments_WFP_E_All_Data_(Normalized).csv
   Recipient Country Code Recipient Country  Item Code             Item  \
0                       2       Afghanistan      10109  Blended And Mix
1                       2       Afghanistan      10109  Blended And Mix

   Donor Country Code Donor Country  Year Code  Year    Unit   Value Flag
0                 500  Total Donors       1990  1990  tonnes  1992.0   XF
1                 500  Total Donors       1999  1999  tonnes  4482.0   XF

./Data/current_FAO/raw_files/Food_Security_Data_E_All_Data_(Normalized).csv
   Area Code         Area  Item Code  \
0          2  Afghanistan      21010
1          2  Afghanistan      21010

                                                Item  Element Code Element  \
0  Average dietary energy supply adequacy (%) (3-...          6121   Value
1  Average dietary energy supply adequacy (%) (3-...          6121   Value

   Year Code       Year Unit  Value Flag
0   19992001  1999-2001    %   89.0    F

In [2]:
crops_normalised_filename="./Data/current_FAO/raw_files/Production_Crops_E_All_Data_(Normalized).csv"
crop_filename="./Data/fao_data_crops_data.csv"

crop_normalised_df=pd.read_csv(crops_normalised_filename,encoding = "ISO-8859-1")
crop_df=pd.read_csv(crop_filename)

In [38]:
crop_normalised_df.head(2)

,Area Code,Area,Item Code,Item,Element Code,Element,Year Code,Year,Unit,Value,Flag
0,2,Afghanistan,221,"Almonds, with shell",5312,Area harvested,1975,1975,ha,0.0,F
1,2,Afghanistan,221,"Almonds, with shell",5312,Area harvested,1976,1976,ha,5900.0,F

In [29]:
crop_normalised_df[['Element','Value']].groupby('Element').sum().sort_values('Value',ascending=False)

                       Value
Element
Production      2.996054e+12
Area harvested  9.142499e+11
Seed            9.317855e+10
Yield           6.928174e+10

In [30]:
crop_normalised_df[['Area','Element','Value']].groupby(['Area','Element']).count()

                            Value
Area        Element
Afghanistan Area harvested   2470
            Production       2578
            Seed              972
            Yield            2467
Africa      Area harvested   8219
...                           ...
Zambia      Yield            2011
Zimbabwe    Area harvested   3438
            Production       3799
            Seed             1134
            Yield            3417

[1003 rows x 1 columns]

In [3]:
crop_types_df=crop_normalised_df[['Item','Value']].groupby('Item').sum().sort_values('Value',ascending=False)

In [4]:
crop_types_df.sample(5)

                               Value
Item
Cucumbers and gherkins  9.207374e+09
Blueberries             9.780348e+07
Buckwheat               1.709648e+09
Vetches                 6.994790e+08
Fruit, pome nes         1.118760e+07

In [13]:
files=[\
      "./Data/current_FAO/raw_files/CommodityBalances_Crops_E_All_Data_(Normalized).csv",\
      "./Data/current_FAO/raw_files/Environment_LandCover_E_All_Data_(Normalized).csv",\
      "./Data/current_FAO/raw_files/Environment_LivestockPatterns_E_All_Data_(Normalized).csv",\
      "./Data/current_FAO/raw_files/Production_Crops_E_All_Data_(Normalized).csv",\
      "./Data/current_FAO/raw_files/Production_CropsProcessed_E_All_Data_(Normalized).csv",\
      "./Data/current_FAO/raw_files/Production_Indices_E_All_Data_(Normalized).csv",\
      "./Data/current_FAO/raw_files/Production_Livestock_E_All_Data_(Normalized).csv",\
      "./Data/current_FAO/raw_files/Production_LivestockPrimary_E_All_Data_(Normalized).csv",\
      "./Data/current_FAO/raw_files/Production_LivestockProcessed_E_All_Data_(Normalized).csv"]

In [5]:
def store_panda_df(url, year, id_conf ):
    
    result = requests.get(url)
    
    soupe = BeautifulSoup(result.text, 'html.parser')
    publications_list = []
    elements = soupe.body.find_all('ul')[1].find_all('li')
    for element in elements:
        
        title = element.find_all('a', href = re.compile("^/paper"))[0].text
        authors_list = element.find_all('a',{"class" : 'author'} )
        
        authors = [author.text for author in authors_list]
        
        publications_list.append({'id': id_conf, 'authors': authors, 'year': year, 'title': title})
        
    publications = pd.DataFrame.from_dict(publications_list)
    
    return publications

In [6]:
from requests import get
import requests
from bs4 import BeautifulSoup
import re

def get_category(url):
    r=requests.get(url)
    soup=BeautifulSoup(r.text,'html.parser')
    categories=soup.body.find_all('a')

In [7]:
url="https://world-crops.com/food-crops/"
r=requests.get(url,headers={"User-Agent": "XY"})
soup=BeautifulSoup(r.text,'html.parser')
elements_temp=soup.find_all('a',href=re.compile("^../"))
elements=[el.text for el in elements_temp]

for i in range(40,401,40):
    url_i=url+"?ss="+str(i)
    r=requests.get(url_i,headers={"User-Agent":"XY"})
    soup=BeautifulSoup(r.text,'html.parser')
    new_elements=soup.find_all('a',href=re.compile("^../"))
    elements+=[el.text for el in new_elements]

In [8]:
elements_stable=elements

TypeError: descriptor 'lower' of 'str' object needs an argument

In [9]:
crop_types_df.index=crop_types_df.index.str.lower()
elements=list(map(lambda x:x.lower(),elements))

In [69]:
def inclusive_search(string,elements):
    
    delimiters = ",", "(","&",")"," and "," "
    pattern = '|'.join(map(re.escape, delimiters))
    strings=list(filter(None,re.split(pattern,string)))
    found=False
    for s in strings:
        if s=="nes":
            continue
        for el in elements:
            found=(s in el.split())
            if found==False and s[-1]=="s":
                found=s[:-1] in el.split()
            if found==False and s[-2:]=="es":
                found=s[:-2] in el.split()
            if found==False and s[-3:]=="ies":
                found=s[:-3]+"y" in el.split()
            if found==True:
                return found
    return found

In [74]:
test=crop_types_df[list(map(lambda x:not inclusive_search(x,elements),crop_types_df.reset_index().Item))]
test

                                   Value
Item
cereals,total               6.476818e+11
coarse grain, total         2.923431e+11
vegetables primary          1.502298e+11
oilcakes equivalent         8.456278e+10
oilcrops primary            6.878902e+10
vegetables, fresh nes       4.365071e+10
pulses,total                3.450090e+10
seed cotton                 2.217389e+10
fibre crops primary         1.607477e+10
sunflower seed              8.716296e+09
cottonseed                  8.608342e+09
cotton lint                 4.470907e+09
treenuts,total              3.139447e+09
sesame seed                 2.886781e+09
rubber, natural             2.848267e+09
tobacco, unmanufactured     2.797420e+09
pulses, nes                 2.687601e+09
grain, mixed                2.039916e+09
cereals, nes                1.923445e+09
linseed                     1.811896e+09
triticale                   1.777634e+09
tea                         1.352003e+09
oilseeds nes                1.099205e+09
walnuts, with shell         7.381000e+08
spices, nes                 7.090535e+08
almonds, with shell         7.077718e+08
vegetables, leguminous nes  5.378411e+08
safflower seed              4.611587e+08
ginger                      4.396691e+08
flax fibre and tow          4.365161e+08
cashewapple                 4.126288e+08
berries nes                 4.035045e+08
bastfibres, other           3.973528e+08
melonseed                   3.772233e+08
sisal                       3.307734e+08
tallowtree seed             2.656204e+08
hazelnuts, with shell       2.550907e+08
fibre crops nes             2.363942e+08
maté                        1.714630e+08
coir                        1.713022e+08
yautia (cocoyam)            1.661249e+08
pistachios                  1.531402e+08
hemp tow waste              1.193344e+08
cloves                      1.082396e+08
peppermint                  9.696537e+07
canary seed                 9.025217e+07
hops                        8.716429e+07
ramie                       7.310367e+07
nutmeg, mace and cardamoms  7.152813e+07
hempseed                    7.101998e+07
manila fibre (abaca)        6.726675e+07
cinnamon (canella)          5.414178e+07
kapokseed in shell          5.059669e+07
poppy seed                  4.169892e+07
agave fibres nes            3.444608e+07
pyrethrum, dried            2.382650e+07
kapok fibre                 2.000016e+07
vanilla                     1.777940e+07
gums, natural               4.113548e+06
jojoba seed                 7.422000e+05

In [66]:
string="coarse and buckle"
"coarse" in string.split()

True

In [249]:
elements

['abiu',
 'acerola',
 'achacha',
 'ackee',
 'african eggplant',
 'african mangosteen',
 'african rice',
 'agati',
 'air potato',
 'alpine currant',
 'amaranthus spp',
 'ambarella',
 'american gooseberry',
 'american groundnut',
 'american oil palm',
 'american persimmon',
 'apple',
 'apricot',
 'arazá',
 'armenian cucumber',
 'arracacha',
 'arrowleaf elephant ear',
 'arrowroot',
 'artichoke',
 'ash gourd',
 'asian palmyra palm',
 'asian pear',
 'asparagus',
 'atemoya',
 'australian desert raisin',
 'avocado',
 'azarole',
 'azuki bean',
 'babaco',
 'bael',
 'bambara groundnut',
 'bamboo',
 'banana',
 'barbados gooseberry',
 'barley',
 'beet',
 'beetroot',
 'bergamot',
 'betel nut',
 'bignay',
 'bilberry',
 'bilimbi',
 'binjai',
 'biriba',
 'bitter gourd',
 'bitter orange',
 'bitter vetch',
 'bitterleaf',
 'black chokeberry',
 'black currant',
 'black mulberry',
 'black mustard',
 'black radish',
 'black salsify',
 'black sapote',
 'blackberry',
 'blanched celery',
 'blue-berried honeysuckle',
 'borojó',
 'breadfruit',
 'broad bean',
 'broccoli',
 'brussels sprout',
 "buck's horn plantain",
 'buckwheat',
 'burmese grape',
 'buttercup squash',
 'butternut squash',
 'button mangosteen',
 'cabbage',
 'cacao',
 'caigua',
 'calabash',
 'calamondin',
 'canistel',
 'cantaloupe',
 'cape gooseberry',
 'capsicum spp',
 'caraway',
 'carob',
 'carrot',
 'cashew nut',
 'cassabanana',
 'cassava',
 'catjang',
 'cauliflower',
 'celeriac',
 'celery',
 'celtuce',
 'cempedak',
 'chard',
 'charichuelo',
 'chayote',
 'cherimoya',
 'cherry',
 'cherry of the rio grande',
 'cherry plum',
 'chia',
 'chickpea',
 'chicory',
 'chilacayote',
 'chili pepper capsicum annuum',
 'chili pepper capsicum baccatum',
 'chili pepper capsicum chinense',
 'chili pepper capsicum frutescens',
 'chili pepper capsicum pubescens',
 'chili peppers',
 'chinese cabbage',
 'chinese hawthorn',
 'chinese potato',
 'chinese water chestnut',
 'chinese white pear',
 'chinese yam',
 'chives',
 'chokeberry',
 'chufa sedge',
 'citron',
 'cocona',
 'coconut',
 'cocoplum',
 'coffee',
 'coffee arabica',
 'coffee robusta',
 'common bean',
 'common purslane',
 'corn salad',
 'costa rica pitahaya',
 'cowpea',
 'cress',
 'cucumber',
 'currants',
 'cushaw pumpkin',
 'custard apple',
 'daikon',
 'date',
 'date-plum',
 'dog rose',
 'dragonfruit',
 'drumstick tree',
 'durian',
 'durum wheat',
 'eggplant',
 'egyptian cucumber',
 'einkorn wheat',
 'elderberry',
 'elephant apple',
 'elephant foot yam',
 'elephant garlic',
 'emmer wheat',
 'endive',
 'enokitake',
 'enset',
 'ethiopian eggplant',
 'european nettle tree',
 'european wild apple',
 'feijoa',
 'fig',
 'finger millet',
 'florence fennel',
 'fluted gourd',
 'fonio',
 'foxtail millet',
 'gac',
 'garden rocket',
 'garlic',
 'genipapo',
 'geocarpa groundnut',
 'giant granadilla',
 'golden oyster mushroom',
 'good king henry',
 'gooseberry',
 'goumi',
 'grape',
 'grapefruit',
 'grass pea',
 'great morinda',
 'greengage',
 'groundnut',
 'grumichama',
 'guar bean',
 'guava',
 'hairy crabgrass',
 'hardy kiwi',
 'horned melon',
 'horse gram',
 'horse mango',
 'horseradish',
 'hyacinth bean',
 'iceplant',
 'indian barnyard millet',
 'indian fig',
 'indian gooseberry',
 'indian jujube',
 'indian oyster',
 'indian spinach',
 'ivy gourd',
 'jabuticaba',
 'jackalberry',
 'jackfruit',
 'jambul',
 'japanese barnyard millet',
 'japanese persimmon',
 'japanese wineberry',
 'jelly ear',
 'jerusalem artichoke',
 "job's tears",
 'jocote',
 'jujube',
 'kaffir lime',
 'kale',
 'karanda',
 'kei apple',
 'kepel apple',
 'key lime',
 'khorasan wheat',
 'king oyster mushroom',
 'kitembilla',
 'kiwifruit',
 'kohlrabi',
 'konjac',
 'korlan',
 'kubal vine',
 'kumquat',
 'kurrat',
 'kuwini mango',
 'kwai muk',
 'langsat',
 'large cranberry',
 'leek',
 'lemon',
 'lentil',
 'lettuce',
 'liberian coffee',
 'lima bean',
 "lion's mane mushroom",
 'longan',
 'loquat',
 'lotus',
 'lychee',
 'maca',
 'maize',
 'malay apple',
 'mamey sapote',
 'mammee apple',
 'mangelwurzel',
 'mango',
 'mangosteen',
 'maprang',
 'marang',
 'mashua',
 'medlar',
 'melon',
 'mirabelle plum',
 'miracle fruit',
 'monk fruit',
 'monkey jack',
 'moriche palm',
 'moso bamboo',
 'moth bean',
 'mountain papaya',
 'mountain soursop',
 'mulberry',
 'mung bean',
 'nance',
 'napa cabbage',
 'naranjilla',
 'natal plum',
 'neem',
 'northern highbush blueberry',
 'oat',
 'oca',
 'oil palm',
 'okra',
 "oldham's bamboo",
 'olive',
 'onion',
 'orange',
 'otaheite gooseberry',
 'oyster mushroom',
 'papaya',
 'para guava',
 'parsnip',
 'passionfruit',
 'pawpaw',
 'pea',
 'peach',
 'peach palm',
 'pear',
 'pearl millet',
 'pepino',
 'pigeon pea',
 'pineapple',
 'pitomba eugenia luschnathiana',
 'pitomba talisia esculenta',
 'plantain',
 'plum',
 'pointed gourd',
 'pomegranate',
 'pomelo',
 'poplar mushroom',
 'potato',
 'proso millet',
 'pulasan',
 'purple chokeberry',
 'quince',
 'quinoa',
 'radish',
 'rambutan',
 'ramontchi',
 'rapeseed',
 'raspberry',
 'red amaranth',
 'red chokeberry',
 'red currant',
 'red mulberry',
 'red-fruited strawberry guava',
 'rhubarb',
 'ribbed gourd',
 'rice',
 'rice bean',
 'root parsley',
 'rose apple',
 'roselle',
 'runner bean',
 'rutabaga',
 'rye',
 'safou',
 'sago palm',
 'salak',
 'salmonberry',
 'salsify',
 'santol',
 'sapodilla',
 'satsuma',
 'scallion',
 'sea kale',
 'seagrape',
 'shallot',
 'snake gourd',
 'snow fungus',
 'snow pea',
 'soncoya',
 'sorghum',
 'sorghum spp',
 'sorrel',
 'sour cherry',
 'soursop',
 'soybean',
 'spanish lime',
 'spanish tamarind',
 'spelt wheat',
 'spilanthes',
 'spinach',
 'spinach beet',
 'star apple',
 'starfruit',
 'strawberry',
 'strawberry guava',
 'strawberry tree',
 'sugar apple',
 'sugar beet',
 'sugarcane',
 'surinam cherry',
 'sweet briar',
 'sweet granadilla',
 'sweet lime',
 'sweet potato',
 'tamarillo',
 'tamarind',
 'tangerine',
 'taro',
 'tarwi',
 'teasle gourd',
 'tef',
 'tepary bean',
 'tinda',
 'tomatillo',
 'tomato',
 'tossa jute',
 'tuberous pea',
 'tucuma palm',
 'turnip',
 'turnip-rooted chervil',
 'urad bean',
 'vaccinium spp',
 'velvet apple',
 'wampee',
 'water caltrop trapa bicornis',
 'water caltrop trapa natans',
 'water morning glory',
 'watercress',
 'watermelon',
 'watery rose apple',
 'wax apple',
 'welsh onion',
 'west african okra',
 'west indian gherkin',
 'wheat',
 'white currant',
 'white goosefoot',
 'white lupin',
 'white mulberry',
 'white sapote',
 'white star apple',
 'white yam',
 'wild rice',
 'winged bean',
 'winter purslane',
 'wolfberry lycium barbarum',
 'wolfberry lycium chinense',
 'yacón',
 'yam',
 'yangmei',
 'yard-long bean',
 'yellow lupin',
 'yellow mombin',
 'yellow pitaya',
 'yellow-fruited strawberry guava',
 'zucchini']